approve:
- lgtm_acts_as_approve: true
  repos:
  - zxDiscovery/lighthouse-config
  - zxDiscovery/hello
  require_self_approval: true
config_updater:
  gzip: false
  maps:
    config.yaml:
      name: config
    plugins.yaml:
      name: plugins
triggers:
- repos:
  - zxDiscovery/hello
  ignore_ok_to_test: false
  elide_skipped_contexts: false
plugins:
  zxDiscovery/lighthouse-config:
  - config-updater
  - approve
  - lgtm
  - trigger
  zxDiscovery/hello:
  - config-updater
  - approve
  - lgtm
  - trigger
